FROM golang:1.12-alpine as builder

ADD . /go-iiif

RUN apk update \
    && apk upgrade \
    && apk add make \
    && cd /go-iiif \
    && make tools

FROM alpine

COPY --from=builder /go-iiif/bin/iiif-server /bin/iiif-server

RUN apk update \
    && apk upgrade \
    && apk add \
    ca-certificates

RUN mkdir /etc/go-iiif
RUN mkdir /usr/local/go-iiif

VOLUME /etc/go-iiif
VOLUME /usr/local/go-iiif

EXPOSE 8080